Repository betaflight/unified-targets, pull requests merged in 2019-10, with the labels that each got.

#37 Added target administrators for DRCL, TTRH.
  .github/CODEOWNERS
Labels: administration

#39 Fixed broken link to target creation instructions.
  README.md
Labels: documentation

#44 Added maintainer for Airbot target configurations.
  .github/CODEOWNERS
  Manufacturers.md
Labels: administration

#48 Added manufacturer id for Lumenier.
  Manufacturers.md
Labels: manufacturer id

#50 Add manufacturer id for DALRC, add target maintainer.
  .github/CODEOWNERS
  Manufacturers.md
Labels: administration, manufacturer id

#55 Add .gitignore to prevent .DS_Store files showing as changes on MacOS
  .gitignore
Labels: housekeeping

#66 Added config for GitHub bots.
  .github/no-response.yml
  .github/stale.yml
Labels: administration

#67 Add OpenPilot (OPEN) manufacturer
  Manufacturers.md
Labels: administration

#78 Added target maintainer for HeliNation.
  .github/CODEOWNERS
Labels: administration

#84 Fixed target paths in 'CODEOWNERS'.
  .github/CODEOWNERS
Labels: administration

#87 Added target maintainer for Lumenier.
  .github/CODEOWNERS
Labels: administration

#90 Added manufacturer id for GetFPV.
  .github/CODEOWNERS
  Manufacturers.md
Labels: administration

#96 Added maintainer for EXUAV / iFlight manufacturers.
  .github/CODEOWNERS
Labels: administration

#97 Added manufacturer id for HIFIONRC.
  .github/CODEOWNERS
  Manufacturers.md
Labels: administration, manufacturer id
