Repository betaflight/unified-targets, pull requests merged in 2021-12, with the labels that each got.

#536 Fix KAKUTEH7MINI
  configs/default/HBRO-KAKUTEH7MINI.config
Labels: bugfix

#542 bugfix for 4.3 - set EXTI to none for NOX
  configs/default/AIRB-NOX.config
Labels: bugfix, tested

#535 Added manufacturer id and maintainer for Axisflying.
  .github/CODEOWNERS
  Manufacturers.md
Labels: administration
