Repository betaflight/unified-targets, pull requests merged in 2021-08, with the labels that each got.

#485 Fixed line endings for RUSRACE targets.
  configs/default/CUST-RUSRACE_F4.config
  configs/default/CUST-RUSRACE_F7.config
Labels: bugfix

#471 FLYWOO F745NANO FC update targets config
  configs/default/FLWO-FLYWOOF745NANO.config
Labels: pinned

#474 Update RAST-AIRF7.config
  configs/default/RAST-AIRF7.config
Labels: rebase required

#490 Added check for the correct file encoding.
  Makefile
  check_targets.sh
Labels: administration

#489 Changed the target maintainer for Foxeer.
  .github/CODEOWNERS
Labels: administration

#482 Fix dma resource (Foxeer F722V2 target config)
  configs/default/FOXE-FOXEERF722V2.config
Labels: bugfix
