Repository betaflight/unified-targets, pull requests merged in 2022-04, with the labels that each got.

#580 Fix beeper on Diatone Mamba MK4 H743
  configs/default/DIAT-MAMBAH743.config
Labels: bugfix

#575 Add Anyleaf manufacturer ID
  .github/CODEOWNERS
  Manufacturers.md
Labels: manufacturer id, Inactive

#578 Add target AOCODARCF7DUAL
  configs/default/SJET-AOCODARCF7DUAL.config
Labels: rebase / squash required
