Repository betaflight/unified-targets, pull requests merged in 2023-01, with the labels that each got.

#771 Add #defines
  configs/default/DAFP-DARWINF4SX1280HD.config
  configs/default/DIAT-MAMBAF405_2022B.config
  configs/default/DIAT-MAMBAF722_I2C.config
  configs/default/FLWO-FLYWOOF745.config
  configs/default/FLWO-FLYWOOF745NANO.config
  configs/default/FLWO-FLYWOOF7DUAL.config
  configs/default/JHEF-JHEF411.config
Labels: build system improvement

#780 UPDATE: Adding defines for cloud build COLIBRI
  configs/default/TEBS-COLIBRI.config
Labels: housekeeping, Missing Information

#781 UPDATE: Adding defines for VIVA-VIVAF4AIO
  configs/default/VIVA-VIVAF4AIO.config
Labels: housekeeping, Missing Information

#828 Update links
  CONTRIBUTING.md
  README.md
Labels: housekeeping
